use std::path::{Path, PathBuf};
use timelayer_agent_sdk::{AgentBundle, CheckResult, StopReason};

const EXAMPLE_BUNDLE: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../example-bundle"
);

/// The verifier binary is an EXTERNAL dependency (timelayer-verifier v2.0.0+),
/// not vendored here. Its path comes from the `TL_VERIFIER_PATH` env var. When
/// the var is unset or points at a missing file, the receipt-verifying tests
/// SKIP (early return with a message) instead of failing — so `cargo test` is
/// green on a machine without the binary.
fn verifier_path() -> Option<PathBuf> {
    let raw = std::env::var("TL_VERIFIER_PATH").ok()?;
    let p = PathBuf::from(raw);
    if p.exists() {
        Some(p)
    } else {
        None
    }
}

/// Returns the verifier path or SKIPs the current test with a clear message.
macro_rules! verifier_or_skip {
    () => {
        match verifier_path() {
            Some(p) => p,
            None => {
                eprintln!(
                    "SKIP: set TL_VERIFIER_PATH to a timelayer-verifier v2.0.0+ binary to run this test"
                );
                return;
            }
        }
    };
}

fn load_bundle(verifier: &Path) -> AgentBundle {
    AgentBundle::load_with_verifier(Path::new(EXAMPLE_BUNDLE), Some(verifier))
        .expect("failed to load example-bundle")
}

#[test]
fn bundle_loads_successfully() {
    let v = verifier_or_skip!();
    let bundle = load_bundle(&v);
    assert_eq!(bundle.manifest.receipt_count, 4);
    assert_eq!(bundle.manifest.topology_id, "topo_project_review_001");
    assert!(!bundle.manifest.agent_can_issue_receipts);
    assert!(bundle.manifest.no_receipt_no_action);
}

#[test]
fn all_actions_allow_with_valid_receipts() {
    let v = verifier_or_skip!();
    let bundle = load_bundle(&v);
    for action_id in bundle.action_ids() {
        match bundle.check_action(action_id) {
            CheckResult::Allow { .. } => {}
            CheckResult::Stop { reason, message, .. } => {
                panic!("action '{action_id}' should be ALLOW but got STOP({reason}): {message}");
            }
        }
    }
}

#[test]
fn missing_action_returns_stop_no_receipt() {
    let v = verifier_or_skip!();
    let bundle = load_bundle(&v);
    match bundle.check_action("action_does_not_exist") {
        CheckResult::Stop { reason, .. } => {
            assert_eq!(reason, StopReason::NoReceipt);
        }
        CheckResult::Allow { .. } => {
            panic!("nonexistent action should return Stop(NoReceipt)");
        }
    }
}

#[test]
fn topology_next_actions_are_correct() {
    let v = verifier_or_skip!();
    let bundle = load_bundle(&v);

    let next = bundle.allowed_next("action_read_files");
    assert!(next.contains(&"action_summarize".to_string()));
    assert!(next.contains(&"action_stop_for_review".to_string()));

    let next2 = bundle.allowed_next("action_create_report");
    assert_eq!(next2, vec!["action_stop_for_review"]);

    // stop has no next
    let next3 = bundle.allowed_next("action_stop_for_review");
    assert!(next3.is_empty());
}

#[test]
fn transition_check_valid_path() {
    let v = verifier_or_skip!();
    let bundle = load_bundle(&v);
    match bundle.check_transition("action_read_files", "action_summarize") {
        CheckResult::Allow { .. } => {}
        r => panic!("expected Allow, got {r:?}"),
    }
}

#[test]
fn transition_check_invalid_path() {
    let v = verifier_or_skip!();
    let bundle = load_bundle(&v);
    // create_report cannot go back to read_files
    match bundle.check_transition("action_create_report", "action_read_files") {
        CheckResult::Stop { reason, .. } => {
            assert_eq!(reason, StopReason::TopologyDenied);
        }
        r => panic!("expected Stop(TopologyDenied), got {r:?}"),
    }
}

#[test]
fn audit_all_passes() {
    let v = verifier_or_skip!();
    let bundle = load_bundle(&v);
    let report = bundle.audit();
    assert_eq!(report.len(), 4);
    for entry in &report {
        assert!(
            entry.is_valid(),
            "action '{}' failed audit: {:?}",
            entry.action_id,
            entry.result
        );
    }
}

#[test]
fn segment_bundle_loads() {
    let v = verifier_or_skip!();
    let segment_path = Path::new(EXAMPLE_BUNDLE).join("exports/segment_01");
    // The segment export is an optional fixture (regenerated by the exporter);
    // if it is not present in this checkout, skip rather than fail.
    if !segment_path.exists() {
        eprintln!("SKIP: example-bundle/exports/segment_01 fixture not present");
        return;
    }
    let bundle = AgentBundle::load_with_verifier(&segment_path, Some(&v))
        .expect("failed to load segment_01");

    assert_eq!(bundle.manifest.bundle_type, "segment");
    assert_eq!(bundle.manifest.actions.len(), 1);

    match bundle.check_action("action_read_files") {
        CheckResult::Allow { .. } => {}
        r => panic!("segment action should be ALLOW, got {r:?}"),
    }
}

#[test]
fn verifier_available() {
    let v = verifier_or_skip!();
    let bundle = load_bundle(&v);
    assert!(
        bundle.verifier_available(),
        "verifier or roster not found"
    );
}
