use std::path::{Path, PathBuf};
use timelayer_agent_sdk::{AgentBundle, CheckResult, StopReason};

const EXAMPLE_BUNDLE: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../example-bundle"
);

/// The verifier binary is an EXTERNAL dependency (timelayer-verifier v2.0.0+),
/// not vendored here. Its path comes from the `TL_VERIFIER_PATH` env var. When
/// the var is unset or points at a missing file, the receipt-verifying tests
/// SKIP (early return with a message) instead of failing — so `cargo test` is
/// green on a machine without the binary.
fn verifier_path() -> Option<PathBuf> {
    let raw = std::env::var("TL_VERIFIER_PATH").ok()?;
    let p = PathBuf::from(raw);
    if p.exists() {
        Some(p)
    } else {
        None
    }
}

/// Returns the verifier path or SKIPs the current test with a clear message.
macro_rules! verifier_or_skip {
    () => {
        match verifier_path() {
            Some(p) => p,
            None => {
                eprintln!(
                    "SKIP: set TL_VERIFIER_PATH to a timelayer-verifier v2.0.0+ binary to run this test"
                );
                return;
            }
        }
    };
}

fn load_bundle(verifier: &Path) -> AgentBundle {
    AgentBundle::load_with_verifier(Path::new(EXAMPLE_BUNDLE), Some(verifier))
        .expect("failed to load example-bundle")
}

#[test]
fn bundle_loads_successfully() {
    let v = verifier_or_skip!();
    let bundle = load_bundle(&v);
    assert_eq!(bundle.manifest.receipt_count, 4);
    assert_eq!(bundle.manifest.topology_id, "topo_project_review_001");
    assert!(!bundle.manifest.agent_can_issue_receipts);
    assert!(bundle.manifest.no_receipt_no_action);
}

#[test]
fn all_actions_allow_with_valid_receipts() {
    let v = verifier_or_skip!();
    let bundle = load_bundle(&v);
    for action_id in bundle.action_ids() {
        match bundle.check_action(action_id) {
            CheckResult::Allow { .. } => {}
            CheckResult::Stop { reason, message, .. } => {
                panic!("action '{action_id}' should be ALLOW but got STOP({reason}): {message}");
            }
        }
    }
}

#[test]
fn missing_action_returns_stop_no_receipt() {
    let v = verifier_or_skip!();
    let bundle = load_bundle(&v);
    match bundle.check_action("action_does_not_exist") {
        CheckResult::Stop { reason, .. } => {
            assert_eq!(reason, StopReason::NoReceipt);
        }
        CheckResult::Allow { .. } => {
            panic!("nonexistent action should return Stop(NoReceipt)");
        }
    }
}

#[test]
fn topology_next_actions_are_correct() {
    let v = verifier_or_skip!();
    let bundle = load_bundle(&v);

    let next = bundle.allowed_next("action_read_files");
    assert!(next.contains(&"action_summarize".to_string()));
    assert!(next.contains(&"action_stop_for_review".to_string()));

    let next2 = bundle.allowed_next("action_create_report");
    assert_eq!(next2, vec!["action_stop_for_review"]);

    // stop has no next
    let next3 = bundle.allowed_next("action_stop_for_review");
    assert!(next3.is_empty());
}

#[test]
fn transition_check_valid_path() {
    let v = verifier_or_skip!();
    let bundle = load_bundle(&v);
    match bundle.check_transition("action_read_files", "action_summarize") {
        CheckResult::Allow { .. } => {}
        r => panic!("expected Allow, got {r:?}"),
    }
}

#[test]
fn transition_check_invalid_path() {
    let v = verifier_or_skip!();
    let bundle = load_bundle(&v);
    // create_report cannot go back to read_files
    match bundle.check_transition("action_create_report", "action_read_files") {
        CheckResult::Stop { reason, .. } => {
            assert_eq!(reason, StopReason::TopologyDenied);
        }
        r => panic!("expected Stop(TopologyDenied), got {r:?}"),
    }
}

#[test]
fn audit_all_passes() {
    let v = verifier_or_skip!();
    let bundle = load_bundle(&v);
    let report = bundle.audit();
    assert_eq!(report.len(), 4);
    for entry in &report {
        assert!(
            entry.is_valid(),
            "action '{}' failed audit: {:?}",
            entry.action_id,
            entry.result
        );
    }
}

#[test]
fn segment_bundle_loads() {
    let v = verifier_or_skip!();
    let segment_path = Path::new(EXAMPLE_BUNDLE).join("exports/segment_01");
    // The segment export is an optional fixture (regenerated by the exporter);
    // if it is not present in this checkout, skip rather than fail.
    if !segment_path.exists() {
        eprintln!("SKIP: example-bundle/exports/segment_01 fixture not present");
        return;
    }
    let bundle = AgentBundle::load_with_verifier(&segment_path, Some(&v))
        .expect("failed to load segment_01");

    assert_eq!(bundle.manifest.bundle_type, "segment");
    assert_eq!(bundle.manifest.actions.len(), 1);

    match bundle.check_action("action_read_files") {
        CheckResult::Allow { .. } => {}
        r => panic!("segment action should be ALLOW, got {r:?}"),
    }
}

// ── P0-01: receipt ↔ action binding (audit 2026-07-11) ─────────────────────

/// Recursive copy of the example bundle into a temp dir we can mutate.
fn copy_bundle_to_tmp() -> tempfile::TempDir {
    fn copy_dir(src: &Path, dst: &Path) {
        std::fs::create_dir_all(dst).unwrap();
        for entry in std::fs::read_dir(src).unwrap() {
            let entry = entry.unwrap();
            let to = dst.join(entry.file_name());
            if entry.file_type().unwrap().is_dir() {
                copy_dir(&entry.path(), &to);
            } else {
                std::fs::copy(entry.path(), &to).unwrap();
            }
        }
    }
    let tmp = tempfile::tempdir().expect("tempdir");
    copy_dir(Path::new(EXAMPLE_BUNDLE), tmp.path());
    tmp
}

#[test]
fn transplanted_receipt_is_refused() {
    let v = verifier_or_skip!();
    let tmp = copy_bundle_to_tmp();
    // A perfectly VALID receipt pair from another action, dropped into this
    // action's directory. The pair verifies in itself — the gate must still
    // refuse, because it does not attest THIS action's intent digest.
    let receipts = tmp.path().join("receipts");
    for f in ["cert.tlcert", "bundle.tlbundle"] {
        std::fs::copy(
            receipts.join("action_summarize").join(f),
            receipts.join("action_read_files").join(f),
        )
        .unwrap();
    }
    let bundle = AgentBundle::load_with_verifier(tmp.path(), Some(&v)).unwrap();
    match bundle.check_action("action_read_files") {
        CheckResult::Stop { reason, .. } => assert_eq!(reason, StopReason::TlsigInvalid),
        CheckResult::Allow { .. } => panic!("receipt transplant must be refused"),
    }
}

#[test]
fn edited_envelope_is_refused() {
    let v = verifier_or_skip!();
    let tmp = copy_bundle_to_tmp();
    // Widen the scope AFTER issuance: read_only -> false. The recomputed
    // intent digest changes, the receipt attests the old one -> STOP.
    let env_path = tmp
        .path()
        .join("receipts/action_read_files/envelope.json");
    let mut v_json: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&env_path).unwrap()).unwrap();
    v_json["scope"]["read_only"] = serde_json::Value::Bool(false);
    v_json["scope"]["write_allowed"] = serde_json::Value::Bool(true);
    std::fs::write(&env_path, serde_json::to_string_pretty(&v_json).unwrap()).unwrap();

    let bundle = AgentBundle::load_with_verifier(tmp.path(), Some(&v)).unwrap();
    match bundle.check_action("action_read_files") {
        CheckResult::Stop { reason, .. } => assert_eq!(reason, StopReason::TlsigInvalid),
        CheckResult::Allow { .. } => panic!("edited envelope must be refused"),
    }
}

#[test]
fn unbound_envelope_policy() {
    let v = verifier_or_skip!();
    let tmp = copy_bundle_to_tmp();
    // Strip every binding from the envelope: no intent_scheme, no
    // tlsig_doc_digest. Default policy: STOP(UnboundReceipt).
    let env_path = tmp
        .path()
        .join("receipts/action_read_files/envelope.json");
    let mut v_json: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&env_path).unwrap()).unwrap();
    v_json.as_object_mut().unwrap().remove("intent_scheme");
    v_json.as_object_mut().unwrap().remove("tlsig_doc_digest");
    std::fs::write(&env_path, serde_json::to_string_pretty(&v_json).unwrap()).unwrap();

    let bundle = AgentBundle::load_with_verifier(tmp.path(), Some(&v)).unwrap();
    match bundle.check_action("action_read_files") {
        CheckResult::Stop { reason, .. } => assert_eq!(reason, StopReason::UnboundReceipt),
        CheckResult::Allow { .. } => panic!("unbound envelope must be refused by default"),
    }

    // Explicit legacy opt-out: TL_AGENT_ALLOW_UNBOUND=1 accepts pair validity.
    // (Set/removed inside this single test to avoid env races across threads.)
    std::env::set_var("TL_AGENT_ALLOW_UNBOUND", "1");
    let allowed = matches!(
        bundle.check_action("action_read_files"),
        CheckResult::Allow { .. }
    );
    std::env::remove_var("TL_AGENT_ALLOW_UNBOUND");
    assert!(allowed, "legacy opt-out must accept a valid unbound pair");
}

#[test]
fn unknown_intent_scheme_is_refused() {
    let v = verifier_or_skip!();
    let tmp = copy_bundle_to_tmp();
    let env_path = tmp
        .path()
        .join("receipts/action_read_files/envelope.json");
    let mut v_json: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&env_path).unwrap()).unwrap();
    v_json["intent_scheme"] = serde_json::Value::String("tl-intent/99".into());
    std::fs::write(&env_path, serde_json::to_string_pretty(&v_json).unwrap()).unwrap();

    let bundle = AgentBundle::load_with_verifier(tmp.path(), Some(&v)).unwrap();
    match bundle.check_action("action_read_files") {
        CheckResult::Stop { reason, .. } => assert_eq!(reason, StopReason::UnboundReceipt),
        CheckResult::Allow { .. } => panic!("unknown scheme must fail closed, not degrade"),
    }
}

#[test]
fn verifier_available() {
    let v = verifier_or_skip!();
    let bundle = load_bundle(&v);
    assert!(
        bundle.verifier_available(),
        "verifier or roster not found"
    );
}
